// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.6
// source: time/time.proto

package time

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TcpClient is the client API for Tcp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TcpClient interface {
	GetSynack(ctx context.Context, in *Syn, opts ...grpc.CallOption) (*Synack, error)
	SendAck(ctx context.Context, in *Ack, opts ...grpc.CallOption) (*Ack, error)
}

type tcpClient struct {
	cc grpc.ClientConnInterface
}

func NewTcpClient(cc grpc.ClientConnInterface) TcpClient {
	return &tcpClient{cc}
}

func (c *tcpClient) GetSynack(ctx context.Context, in *Syn, opts ...grpc.CallOption) (*Synack, error) {
	out := new(Synack)
	err := c.cc.Invoke(ctx, "/time.tcp/getSynack", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tcpClient) SendAck(ctx context.Context, in *Ack, opts ...grpc.CallOption) (*Ack, error) {
	out := new(Ack)
	err := c.cc.Invoke(ctx, "/time.tcp/sendAck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TcpServer is the server API for Tcp service.
// All implementations must embed UnimplementedTcpServer
// for forward compatibility
type TcpServer interface {
	GetSynack(context.Context, *Syn) (*Synack, error)
	SendAck(context.Context, *Ack) (*Ack, error)
	mustEmbedUnimplementedTcpServer()
}

// UnimplementedTcpServer must be embedded to have forward compatible implementations.
type UnimplementedTcpServer struct {
}

func (UnimplementedTcpServer) GetSynack(context.Context, *Syn) (*Synack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSynack not implemented")
}
func (UnimplementedTcpServer) SendAck(context.Context, *Ack) (*Ack, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAck not implemented")
}
func (UnimplementedTcpServer) mustEmbedUnimplementedTcpServer() {}

// UnsafeTcpServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TcpServer will
// result in compilation errors.
type UnsafeTcpServer interface {
	mustEmbedUnimplementedTcpServer()
}

func RegisterTcpServer(s grpc.ServiceRegistrar, srv TcpServer) {
	s.RegisterService(&Tcp_ServiceDesc, srv)
}

func _Tcp_GetSynack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Syn)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcpServer).GetSynack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.tcp/getSynack",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcpServer).GetSynack(ctx, req.(*Syn))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tcp_SendAck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Ack)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TcpServer).SendAck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/time.tcp/sendAck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TcpServer).SendAck(ctx, req.(*Ack))
	}
	return interceptor(ctx, in, info, handler)
}

// Tcp_ServiceDesc is the grpc.ServiceDesc for Tcp service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tcp_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "time.tcp",
	HandlerType: (*TcpServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "getSynack",
			Handler:    _Tcp_GetSynack_Handler,
		},
		{
			MethodName: "sendAck",
			Handler:    _Tcp_SendAck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "time/time.proto",
}
